In [1]:
import pandas as pd
import numpy as np
import os


Bad pipe message: %s [b'\xf9\x8b\xee/\x9dp\x06\xf4\x89\xf0\x81\x14n\xcb_\x06\xe3| F\xa7mf\x80']
Bad pipe message: %s [b'K\x10>\xbf8\x01k\xee\xe5AG&x\xdb\xc4\xd0\x9c\xbc\x97\xad\tNL\xee\x92\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x00+\x00\x03\x02\x03\x04\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 \xfe\xe8=\x0bb\x8f\xe3\xdb\xaa\x8e\xd9v\t\xc5\xdbi+(']
Bad pipe message: %s [b'\x8f']
Bad pipe message: %s [b'\x0c\x8a1\x83\x04']
Bad pipe message: %s [b"\x97P\x81bJ/mp<\x1ao\x00\x00\xa6\xc0,\xc00\x00\xa3\x00\x9f\xcc\xa9\xcc\xa8\xcc\xaa\xc0\xaf\xc0\xad\xc0\xa3\xc0\x9f\xc0]\xc0a\xc0W\xc0S\xc0+\xc0/\x00\xa2\x00\x9e\xc0\xae\xc0\xac\xc0\xa2\xc0\x9e\xc0\\\xc0`\xc0V\xc0R\xc0$

In [5]:
import torch
x=torch.tensor([[9.9635e-01, 1.5747e-08, 3.4503e-07, 1.9508e-05, 3.6248e-03, 4.4441e-07]])
#x=torch.tensor([[1, 0,0, 0, 0, 0]])
y= torch.tensor([1])
cr= torch.nn.CrossEntropyLoss()

cr(x,y)

tensor(2.0428)

In [4]:
DATA_DIR= "../../../datashare/"

In [5]:
!cd ../../../datashare/


In [9]:
os.listdir(DATA_DIR+"APAS"+"/features")

['fold0', 'fold1', 'fold2', 'fold3', 'fold4']

In [15]:
fold0=os.listdir(DATA_DIR+"APAS"+"/features"+"/fold0")

In [16]:
fold1=os.listdir(DATA_DIR+"APAS"+"/features"+"/fold1")

In [11]:
a=np.load(DATA_DIR+"APAS"+"/features"+"/fold0"+"/P016_balloon1.npy")

In [13]:
a.shape

(1280, 4450)

In [19]:
tmp=[f  for f in fold1 if f not in fold0]

In [20]:
len(tmp) 

0

In [21]:
len(fold0)

96

In [22]:
a=np.load(DATA_DIR+"APAS"+"/features"+"/fold1"+"/P016_balloon1.npy")

(1280, 4450)

In [26]:
a[:,1]

array([ 0.5134662 ,  0.05180113, -0.23709771, ...,  0.05522139,
        0.51376534, -0.19677979], dtype=float32)

In [28]:
os.listdir(DATA_DIR+"APAS")

['features',
 'folds',
 'frames',
 'gestures definitions.txt',
 'kinematics',
 'kinematics_npy',
 'mapping_gestures.txt',
 'mapping_tools.txt',
 'transcriptions_gestures',
 'transcriptions_tools_left_new',
 'transcriptions_tools_right_new']

In [35]:
os.listdir(DATA_DIR+"APAS"+"/frames/P016_balloon1_top")

['img_00001.jpg',
 'img_00002.jpg',
 'img_00003.jpg',
 'img_00004.jpg',
 'img_00005.jpg',
 'img_00006.jpg',
 'img_00007.jpg',
 'img_00008.jpg',
 'img_00009.jpg',
 'img_00010.jpg',
 'img_00011.jpg',
 'img_00012.jpg',
 'img_00013.jpg',
 'img_00014.jpg',
 'img_00015.jpg',
 'img_00016.jpg',
 'img_00017.jpg',
 'img_00018.jpg',
 'img_00019.jpg',
 'img_00020.jpg',
 'img_00021.jpg',
 'img_00022.jpg',
 'img_00023.jpg',
 'img_00024.jpg',
 'img_00025.jpg',
 'img_00026.jpg',
 'img_00027.jpg',
 'img_00028.jpg',
 'img_00029.jpg',
 'img_00030.jpg',
 'img_00031.jpg',
 'img_00032.jpg',
 'img_00033.jpg',
 'img_00034.jpg',
 'img_00035.jpg',
 'img_00036.jpg',
 'img_00037.jpg',
 'img_00038.jpg',
 'img_00039.jpg',
 'img_00040.jpg',
 'img_00041.jpg',
 'img_00042.jpg',
 'img_00043.jpg',
 'img_00044.jpg',
 'img_00045.jpg',
 'img_00046.jpg',
 'img_00047.jpg',
 'img_00048.jpg',
 'img_00049.jpg',
 'img_00050.jpg',
 'img_00051.jpg',
 'img_00052.jpg',
 'img_00053.jpg',
 'img_00054.jpg',
 'img_00055.jpg',
 'img_0005

In [34]:
import cv2

In [36]:
img = cv2.imread(DATA_DIR+"APAS"+"/frames/P016_balloon1_top/img_00001.jpg")
img.shape

(480, 640, 3)

In [40]:
frameSize = (480, 640)

out = cv2.VideoWriter('output_video.avi',cv2.VideoWriter_fourcc(*'DIVX'),  30, frameSize)
i=0
for filename in os.listdir(DATA_DIR+"APAS"+"/frames/P016_balloon1_top"):
    img = cv2.imread(DATA_DIR+"APAS"+"/frames/P016_balloon1_top/"+filename)
    if i%300 == 0:
        print(filename)
    out.write(img)
    i+=1
out.release()

img_00001.jpg


KeyboardInterrupt: 

In [50]:
frameSize = (480, 640)

out = cv2.VideoWriter('output_video.avi',cv2.VideoWriter_fourcc(*'DIVX'), 60, frameSize)
i=0
for filename in os.listdir(DATA_DIR+"APAS"+"/frames/P016_balloon1_side"):
    
    img = cv2.imread(DATA_DIR+"APAS"+"/frames/P016_balloon1_side/"+filename)
    out.write(img)
    if i> 500:
        break
    i+=1
out.release()

In [52]:
cap = cv2.VideoCapture('output_video.avi')

while(cap.isOpened()):
    ret, frame = cap.read()

    print(frame.shape)
    cv2.imshow("frame",frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break



AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
def get_features(filename):
    

In [1]:
cap.read()

NameError: name 'cap' is not defined

In [ ]:
import torch 
import pandas
from model import GreyNet

In [2]:

torch.load("models/model_test.pt")

In [3]:
model.

OrderedDict([('fc1.weight',
              tensor([[ 0.0606,  0.1157, -0.0253,  ..., -0.0629, -0.1390, -0.0425],
                      [ 0.0610, -0.1600, -0.1279,  ..., -0.1524, -0.1438,  0.0069],
                      [ 0.0164, -0.1128, -0.0494,  ...,  0.0522,  0.0640,  0.0623],
                      ...,
                      [ 0.0242,  0.0189,  0.0229,  ..., -0.0646,  0.0400,  0.0093],
                      [-0.1351,  0.1131,  0.1657,  ...,  0.0934, -0.0907,  0.0892],
                      [ 0.1124, -0.1367,  0.0761,  ...,  0.1042, -0.1368, -0.1386]],
                     device='cuda:0')),
             ('fc1.bias',
              tensor([ 0.1187, -0.0157,  0.1411, -0.0057,  0.1223, -0.0872,  0.0645,  0.1821,
                      -0.0684, -0.0946, -0.1383, -0.0948,  0.0914, -0.1208,  0.0194,  0.1071,
                      -0.0942, -0.0558, -0.1148, -0.0855, -0.1746, -0.1680,  0.1540, -0.1349,
                       0.0224, -0.0794,  0.0173, -0.0041, -0.0163,  0.0837, -0.1032, -0.1520